(env) âžœ  ~ python aws-priceing/openstack_aws_pricing_tool.py --cloud dc1-cdl-osp4 --project osp-c1npgt04-Infr-Arch --aws-csv aws-priceing/AmazonEC2-pricing-20250505.csv
Traceback (most recent call last):
  File "/home/srini/env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Price Description'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "aws-priceing/openstack_aws_pricing_tool.py", line 134, in <module>
    try:main()
  File "aws-priceing/openstack_aws_pricing_tool.py", line 127, in main
    df=build(conn,pid,a.aws_csv)
  File "aws-priceing/openstack_aws_pricing_tool.py", line 90, in build
    od,ri,spec,gp3=_pricing(_load_csv(csv))
  File "aws-priceing/openstack_aws_pricing_tool.py", line 63, in _pricing
    (inst['Price Description'].str.contains('per On Demand', case=False, na=False))]
  File "/home/srini/env/lib/python3.8/site-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/srini/env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'Price Description'
